[package]
name = "sqlx-test-example"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
sqlx = { version = "0.8.1", features = ["runtime-tokio", "postgres"] }

[workspace]
